- name: "install cloudwatch agent"
  dnf:
    name: amazon-cloudwatch-agent
    state: latest

- name: "enable cloudwatch agent"
  systemd:
    name: amazon-cloudwatch-agent
    enabled: true

- name: "set conf"
  template:
    src: cloudwatch.conf.j2
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: 0644

- name: "restart cloudwatch agent"
  systemd:
    name: amazon-cloudwatch-agent
    state: restarted
  changed_when: false
