- hosts: all
  connection: local
  become: yes

  vars:
    group: central

  vars_files:
    - group_vars/{{ env }}/main.yml
    - group_vars/{{ env }}/central.yml

  roles:
    - { role: rsyslog_setup, tags: rsyslog_setup }
    - { role: cloudwatch_setup, tags: cloudwatch_setup }
    - { role: locale_setup, tags: locale_setup }
    - { role: timezone_setup, tags: timezone_setup }
