- hosts: [central]
  connection: local
  become: yes

  vars_files:
    - group_vars/{{ env }}/main.yml
    - group_vars/{{ env }}/central.yml

  roles:
    - { role: dnf_update, tags: dnf_update }
    - { role: rsyslog_setup, tags: rsyslog_setup }
    - { role: cloudwatch_setup, tags: cloudwatch_setup }
